# By Harsh H. Rajpurohit
name: vpn_basic_project
description: Flutter Android VPN based on OpenVPN Library.
publish_to: 'none'

# App Version
version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

# App dependencies
dependencies:
  flutter:
    sdk: flutter

  #GetX for state management
  get: ^4.6.6

  # Cupertino Style Icons
  cupertino_icons: ^1.0.2

  #For API Call
  http: ^1.1.0

  #Converting CSV to List 
  csv: ^5.1.1

  #For Lottie Animation 
  lottie: ^2.7.0

  #hive data package for caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #url launcher
  url_launcher: ^6.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Change package name  
  # change_app_package_name: ^1.1.0


flutter:
  # Enabling material design
  uses-material-design: true

  # App assets
  assets:
    - assets/
    - assets/vpn/
    - assets/images/
    - assets/lottie/
    - assets/flags/